const ALBUM = `${process.env.S3_IMG_DIR_BASEURL}/${process.env.RALPH_RESOURCE_ALBUM}/static`;
module.exports = {
    UPLOAD_MAX_COUNT: 1,
    MSG_UPLOAD_RESULT_FAIL: 'File Upload Failed',
    IMG_DEFAULT_REWARD_PORTRAIT:`${ALBUM}/gift-voucher-default.png`,
    IMG_DEFAULT_REWARD_LANDSCAPE:`${ALBUM}/gift-voucher-default-wide.png`,
    MSG_RATIO_PORTRAIT: 'Please maintain 1:1 aspect ratio',
    MSG_RATIO_LANDSCAPE: 'Please maintain 3:2 aspect ratio',
    MSG_INVENTORY_MODIFIED: 'Total Inventory was already modified, please try again with the latest inventory',
    MSG_FILE_PNG: 'image/png as file type',
    MSG_FILE_IMAGE: 'any image file type',
    MSG_FILE_CSV: 'Upload file should be \'text/csv\' ',
    MSG_UPDATE_NO_RECORD: 'No Record Found To Update',
    MSG_NO_RECORD: 'No Record/Job Found',
    MSG_ADD_SUCCESS: 'Successfully Added Record',
    MSG_UPDATE_SUCCESS: 'Successfully Updated',
    MSG_DELETE_SUCCESS: 'Successfully Deleted Record',
    MSG_NO_PRIZEID: 'No Prize ID Provided',
    MSG_INVALID_ID: 'Invalid ID Provided, please enter 1 and higher',
    MSG_WHEEL_OPTION_INVALID: 'One of your Wheel Options is invalid. Please  check your data and try again',
    MSG_NO_DATA: 'No Data Provided to Update. Please Check and Try Again.',
    MSG_DELETE_NO_DATA: 'No Record Found To Delete',
    MSG_REWARD_IMAGE_INVALID_URL : 'Invalid Reward Image (portrait/landscape) URL Provided',
    MSG_INVALID_CENTER_IMG: 'Invalid Center Image URL Provided',
    MSG_PROMOCODE_INVALID_HEADER: 'Promo Code Uploaded has invalid header format. Accepted Format: <\'Promo_Code\', \'Activation_At\', \'Expiry_At\'>',
    MSG_PROMOCODE_INVALID_ROWS: ' Promo Code Uploaded has empty rows or rows more than 5000',
    NUM_RATIO_PORTRAIT: 1.00,
    NUM_RATIO_LANDSCAPE: 1.50,
    NUM_724: 724,
    NUM_136: 136,
    NUM_501: 501,
    NUM_334: 334,
    MSG_QUE_SUCCESS: 'Successfully added the file in QUE. We will notify once the job is done.',
    MSG_QUE_ONGOING: 'Job In-Progress',
    MSG_QUE_COMPLETED: 'Job Completed',
    MSG_EVOUCHER_NOTFOUND: 'Evoucher Prize ID not found or deleted',
    MSG_INVALID_QUESTATUS: 'Invalid Status',
    MSG_INVALID_NUMBER: 'Invalid Number Provided',
    MSG_INVALID_PROMO_DATES_CODE: 'The Promo Code, Activation At, Expiry At is empty or has invalid value',
    MSG_INVALID_PROMO_FAILURE: 'The prize create is not an E-Voucher or the upload is not define to be a unique deal or not',
    MSG_INVALID_URL: 'Invalid URL Provided',
    MSG_INVALID_NO_RECORD_SAME_STATUS: 'No Record/Job Found, please check your job id / status should not be the same with the previous status',
    MSG_SET_JOB_STATUS: 'Successfully set the job status to new status',
    MSG_SEND_FAILED_REDIS: 'Successfully added the promocodes to que but fail to send it to the REDIS consumer',
    MSG_FAILED_PROMO_UPLOAD: 'Promo Codes upload has invalid format or missing. Total Rows should be from 1 to 5000. Accepted Format: <\'Promo_Code\', \'Activation_At\', \'Expiry_At\'>',
    TEXT_STATUS_DELETED: 'Deleted',
    TEXT_STATUS_PENDING: 'Pending',
    TEXT_STATUS_INPROGRESS: 'In-Progress',
    TEXT_STATUS_OUTSTANDING: 'Outstanding',
    TEXT_STATUS_COMPLETED: 'Completed',
    TEXT_STATUS_ACTIVE: 'Active',
    MSG_INVALID_INVENTORY: 'Invalid Number Provided, only accepts from 1 to 5000',
    MSG_INVALID_IMAGE: 'Invalid Image Url Provided, please try again',
    MSG_WENT_WRONG: 'Something Went Wrong',

    MSG_NOT_REGISTERED: 'User not registered/activated yet',
    MSG_ACCOUNT_EXISTS: 'Account already exists, please login to continue',
    INVALID_ROLE: 'Invalid role provided',
    MSG_USER_STATUS_FAIL: 'Invalid Verification Code / User ID / status provided',
    MSG_LOGGED_IN_SUCCESS: 'Logged in successfully',
    MSG_SUCCESS: 'Successfully Save',
    MSG_UNDEFINED_FROM_STATUS: 'Un-defined from status',
    BEEQUE_CONNECTION_FAILURE: 'Unable to established Que Connection',
    MSG_UNDEFINED_VARIABLE: 'is undefined / null',


    /* Food Categories */

    MSG_FOOD_CATEGORIYNOT_INSERTED: 'Food Category not inserted!',
};