module.exports = {
    OK_STATUS_CODE: 200,
    CREATED_STATUS_CODE: 201,
    UNAUTHORIZED_STATUS_CODE: 401,
    VALIDATION_ERROR_CODE: 422,
    PAGE_NOT_FOUND_STATUS_CODE: 404,
    SERVER_ERROR_STATUS_CODE: 500,
    ACCEPTED_STATUS_CODE: 202,
};